### ISSUE TITLE
Maximum number of simultaneous connections per IP address disconnecting before limit.

### ISSUE THREAD

**Issue by peter-korinek** [haraka/haraka-plugin-limit#2]
Hi!
We are trying to implement the limit plugin (version 1.0.2), but it is disconnecting to soon. Maybe as soon as 8 concurrent connections.

Our limit.ini consist only of two rows.
[concurrency]
max=500

What are we doing wrong?
Please advise!
:) Peter

We use Haraka Version: 2.8.13

Attached, limit.ini, plugins and example from our log

[limit.ini.txt](https://github.com/haraka/haraka-plugin-limit/files/832496/limit.ini.txt)
[plugins.txt](https://github.com/haraka/haraka-plugin-limit/files/832497/plugins.txt)
[example_from_log.txt](https://github.com/haraka/haraka-plugin-limit/files/832499/example_from_log.txt)

**Comment by msimerson** [comment]
> "421 connection rate limit exceeded"

You aren't hitting concurrency limits, you're hitting the rate limits. Have a look at the default limit.ini file and then raise the rate limits.

**Comment by msimerson** [comment]
Follow up here if you require more assistance.

**Comment by msimerson** [comment]
@peter-korinek , does #3 make this plugin work more like you expected?
