### ISSUE TITLE
what does 127 means in the limit.ini file?

### ISSUE THREAD

**Issue by danieltigse** [haraka/haraka-plugin-limit#25]
I am sorry for asking here but I didn't find another way

**Comment by msimerson** [comment]
It's a network prefix, shorthand for 127.0.0.0/8, or all of the 127 network (loopback).

**Comment by danieltigse** [comment]
Do you mind if I ask you a couple of questions here?

1) What is the use of that network prefix? Basically I just need to limit the number of emails a user can receive. I suppose I need to use the following config
```
[rate_rcpt]
enabled=true
127=0
; 50 emails in 5 minutes
default=50/5m
```
2) If I want to use the karma plugin too. Do I need to use the same db number in the redis config (I know It should be the same redis IP and port)?

**Comment by msimerson** [comment]
1. It lets you treat different networks with different policies. 
2. Doesn't matter. Much. The karma plugin prefixes all its entries so there won't be any conflicts.
