### ISSUE TITLE
Limit users to only send emails from a specified domain

### ISSUE THREAD

**Issue by wioxjk** [haraka/haraka-plugin-limit#28]
It would be really great, if we could limit users to only send emails from a specified domain.

For example, if a user is specified as following in `auth_flat_file.ini:`
`relay@example.com=password`

The user is only allowed to send emails from "example.com".

**Comment by msimerson** [comment]
@wioxjk, please have a look at https://github.com/haraka/Haraka/pull/3265. I could have put that in this plugin, but as it depends on the auth implementation, it just seemed like it belonged better in auth_base.

**Comment by msimerson** [comment]
closing as completed.
