### ISSUE TITLE
Redis camel case errors

### ISSUE THREAD

**Issue by DoobleD** [haraka/haraka-plugin-limit#47]
Hi @msimerson, Happy New Year!

I've observed redis errors with the plugin (using Haraka [2.8.28](https://github.com/haraka/Haraka/releases/tag/2.8.28)), looking like that:

`err:TypeError: this.db.hIncrBy is not a function, rate_conn:TypeError: this.db.hGetAll is not a function`

**Comment by msimerson** [comment]
That's because an older (v3) version of redis is installed. Check out the latest from haraka/master to avoid that.
